language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# run test
script:
  - coverage run --source=app/controllers -m py.test && coverage report
  - coveralls

after_success:
  - coveralls

services:
  - postgresql

addons:
  # postgresql: "9.6"
  # postgresql: "9.5"
  postgresql: "9.4"

env:
  - DB=postgresql://postgres@localhost:5432/travis_ci_test
