language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# run test
script:
  - coverage run --source=app/controllers -m py.test && coverage report
  - coveralls

after_success:
  - coveralls
  
env:
  - DB=postgres
