"""empty message

Revision ID: 5c93568326e8
Revises: afd53109e651
Create Date: 2017-08-07 07:46:40.944194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c93568326e8'
down_revision = 'afd53109e651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bucketlist', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlist', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bucketlist', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
